sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile
  - echo -e "markdown: kramdown # 数学表达式 \n\ninclude: \n- \"_*.html\"" > _config.yml       # add _config on gh-pages branch

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    
notifications:
  email: false
