sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  verbose: 
    - echo "$(curl -fsSL https://longshilin.com/files/config.yml)" > docs/html/_config.yml
  on:
    branch: master
    
notifications:
  email: false
